version: '3.8'

services:
  gin-backend:
    build:
      context: ./backend
    container_name: gin-backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/main
    restart: always
  frontend:
    build: ./frontend
    ports:
      - "3456:3456"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["npm", "run", "dev"]